// a-z, A-Z 0-9, $,_
	var pr = "ff";
    var peremennaya2 = 11;
    var myBoolean = true; //false
    var myNull = null;
    var myUndefined = undefined;
    var myObject = {
        name: "Imya",
        age: 25
    };
    //
    var result = 30 + 20;
   // alert(result);
// console.log(55 - peremennaya2);
peremennaya2 += 9;
//console.log(peremennaya2);
//alert(myObject);


   // alert(Math.round(5.99)); //okryglenie
    var wswww = 11.45667;
 // console.log(pr + "2");

//масиви
var names =["john", "nick", "kait"];
//console.log(names[2].toUpperCase());

//var i = 0;
//while (i < 10) {
//	console.log(i);
//	 i++
//}
function sum(x, y) {
	console.log(x + y);
}
sum(10, 59);